import {
  DEFAULT_ANIMATION_SPEED_FACTOR,
  DEFAULT_GAME_MODE,
  DEFAULT_MAP_KEY,
  DEFAULT_FREE_PLAY_MODE,
  DEFAULT_FREE_PLAY_TEAM_SIZE,
  GAME_VIEW_MODES,
  HUMAN_TURN_BEHAVIORS,
  LEVEL_RESULT,
  LEVEL_STATUS,
  MAIN_GAME_STATES,
  MAPS,
  POINTS_TO_WIN,
  TURN_STATES
} from "../config/constants.js";
import { loadPreference, parseBoolean, PREF_KEYS } from "../ui/preferences.js";

export function createInitialState() {
  return {
    teams: {},
    allRunners: [],
    gameFlags: {},
    barriers: [],
    currentTurnEventLog: [],
    lastTurnEventLog: [],
    lastTurnNarrationText: "",
    narrationVisibleStrip: loadPreference(PREF_KEYS.TURN_LOG_VISIBLE, false, parseBoolean),
    activeRunnerIndex: 0,
    currentTurnNumber: 1,
    currentTurnState: TURN_STATES.SETUP_DISPLAY,
    queuedActionForCurrentRunner: null,
    mainGameState: MAIN_GAME_STATES.SETUP,
    currentGameMode: DEFAULT_GAME_MODE,
    currentMapKey: DEFAULT_MAP_KEY,
    gameMap: MAPS[DEFAULT_MAP_KEY],
    freePlayMode: DEFAULT_FREE_PLAY_MODE,
    freePlayTeamSize: DEFAULT_FREE_PLAY_TEAM_SIZE,
    freePlayMapKey: DEFAULT_MAP_KEY,
    activeBlocklyTeamTab: 1,
    freePlayPrograms: {
      player: "",
      team1: "",
      team2: ""
    },
    animationSpeedFactor: DEFAULT_ANIMATION_SPEED_FACTOR,
    activeBlocklyTrace: null,
    tracePlaybackSteps: [],
    traceStepIndex: 0,
    traceStepFrameCount: 0,
    traceStepFrameBudget: 0,
    traceCurrentBlockId: null,
    traceOverflowBadgeVisible: false,
    traceEmptyHintVisible: false,
    teamScores: { 1: 0, 2: 0 },
    lastScoringTeam: null,
    // Legacy debug flag only; readiness is derived from teamAreaFreezeNextAvailableTurn via isAreaFreezeReady().
    teamAreaFreezeUsed: { 1: false, 2: false },
    teamAreaFreezeNextAvailableTurn: { 1: 1, 2: 1 },
    areaFreezeEffect: null,
    activeJumpLandingDust: null,
    pointsToWin: POINTS_TO_WIN,
    currentModeView: GAME_VIEW_MODES.GUIDED_LEVELS,
    levels: [],
    levelProgress: {},
    currentLevelId: null,
    currentLevelStatus: LEVEL_STATUS.LOCKED,
    activeLevelResult: LEVEL_RESULT.NONE,
    levelAttemptCount: 0,
    currentLevelStartTurnNumber: null,
    lastLevelResultReason: null,
    predictionForCurrentLevel: null,
    currentToolboxBlockTypes: [],
    currentSensorObjectTypes: [],
    currentSensorRelationTypes: [],
    currentMoveTowardTargetTypes: [],
    autoStayHumanRunnerIds: [],
    guidedLevelDevAccessActive: false,
    guidedLevelDevAccessLevelId: null,
    guidedLevelBlocklyAssistActive: false,
    guidedLevelBlocklyAssistApplied: false,
    guidedLevelBlocklyAssistLevelId: null,
    activeTeamSetup: null,
    activeFlagSetup: null,
    setupBarriers: [],
    relayRaceProgress: null,
    humanTurnBehavior: HUMAN_TURN_BEHAVIORS.AUTO_SKIP,
    tutorialSeen: {},
    activeTutorial: null,
    spotlightRect: null,
    goalBurstEffect: null,
    soundEnabled: loadPreference(PREF_KEYS.SOUND_ENABLED, true, parseBoolean),
    showModePicker: true,
    shellReady: false,
    editorReady: false,
    boardReady: false,
    editorLoadError: null,
    boardLoadError: null,
    workspaceImportStatus: null,
    usageExportStatus: null,
    usageTrackerReady: false,
    randomFn: Math.random,
    runnerActionHistory: {},
    lastBlocklyTrace: null,
    classifierRecurrenceState: { counters: {}, perLevelAttempt: {}, perMatch: {} },
    coachingModeEnabled: loadPreference(PREF_KEYS.COACHING_MODE_ENABLED, false, parseBoolean),
    lowMotionOverride: loadPreference(PREF_KEYS.LOW_MOTION_OVERRIDE, false, parseBoolean),
    runnerMovementAnimations: loadPreference(PREF_KEYS.RUNNER_MOVEMENT_ANIMATIONS, true, parseBoolean),
    runnerJumpingAnimations: loadPreference(PREF_KEYS.RUNNER_JUMPING_ANIMATIONS, true, parseBoolean),
    showFrozenBadges: loadPreference(PREF_KEYS.SHOW_FROZEN_BADGES, true, parseBoolean),
    showRunnerIndexBadges: loadPreference(PREF_KEYS.SHOW_RUNNER_INDEX_BADGES, false, parseBoolean),
    lastCoachingText: ""
  };
}

export function createApp() {
  return {
    state: createInitialState(),
    ui: {},
    blocklyWorkspace: null,
    blocklyKeyboardNavigation: null,
    p5Instance: null,
    syncUi: () => {},
    hooks: {}
  };
}
