import { BLOCK_TYPES } from "../../constants.js";
import {
  ADVANCED_ALL_BLOCKS,
  AREA_FREEZE_BLOCKS,
  GENERIC_SENSOR_BLOCKS,
  EXTENDED_MOVEMENT_BLOCKS,
  MOVE_TOWARD_BLOCKS,
  ADVANCED_CAPSTONE_BLOCKS
} from "./toolboxes.js";

export const STRATEGY_BRAIN_PROJECT_TOOLBOX_BLOCKS = [
  ...ADVANCED_ALL_BLOCKS,
  BLOCK_TYPES.IF_HAVE_ENEMY_FLAG,
  BLOCK_TYPES.IF_HAVE_ENEMY_FLAG_ELSE,
  ...GENERIC_SENSOR_BLOCKS,
  ...MOVE_TOWARD_BLOCKS,
  ...AREA_FREEZE_BLOCKS,
  ...EXTENDED_MOVEMENT_BLOCKS
];

export const TEAM_STRATEGY_SCRIPT_PROJECT_TOOLBOX_BLOCKS = [...ADVANCED_CAPSTONE_BLOCKS];
