import { BLOCK_TYPES } from "../../constants.js";

export const BASIC_MOVEMENT_BLOCKS = [
  BLOCK_TYPES.MOVE_FORWARD,
  BLOCK_TYPES.MOVE_UP_SCREEN,
  BLOCK_TYPES.MOVE_DOWN_SCREEN,
  BLOCK_TYPES.STAY_STILL
];

export const EXTENDED_MOVEMENT_BLOCKS = [
  BLOCK_TYPES.MOVE_FORWARD,
  BLOCK_TYPES.MOVE_BACKWARD,
  BLOCK_TYPES.MOVE_UP_SCREEN,
  BLOCK_TYPES.MOVE_DOWN_SCREEN,
  BLOCK_TYPES.STAY_STILL
];

export const GENERIC_SENSOR_BLOCKS = [
  BLOCK_TYPES.IF_SENSOR_MATCHES,
  BLOCK_TYPES.IF_SENSOR_MATCHES_ELSE
];

export const MOVE_TOWARD_BLOCKS = [BLOCK_TYPES.MOVE_TOWARD];

export const JUMP_BLOCKS = [BLOCK_TYPES.JUMP_FORWARD];

export const JUMP_CONDITION_BLOCKS = [
  BLOCK_TYPES.IF_CAN_JUMP,
  BLOCK_TYPES.IF_CAN_JUMP_ELSE
];

export const BARRIER_PLACEMENT_BLOCKS = [BLOCK_TYPES.PLACE_BARRIER];

export const BARRIER_READY_BLOCKS = [
  BLOCK_TYPES.IF_CAN_PLACE_BARRIER,
  BLOCK_TYPES.IF_CAN_PLACE_BARRIER_ELSE
];

export const TEAMMATE_FLAG_BLOCKS = [
  BLOCK_TYPES.IF_TEAMMATE_HAS_FLAG,
  BLOCK_TYPES.IF_TEAMMATE_HAS_FLAG_ELSE
];

export const TERRITORY_BLOCKS = [
  BLOCK_TYPES.IF_ON_MY_SIDE,
  BLOCK_TYPES.IF_ON_MY_SIDE_ELSE,
  BLOCK_TYPES.IF_ON_ENEMY_SIDE,
  BLOCK_TYPES.IF_ON_ENEMY_SIDE_ELSE
];

export const AREA_FREEZE_BLOCKS = [
  BLOCK_TYPES.FREEZE_OPPONENTS,
  BLOCK_TYPES.IF_AREA_FREEZE_READY,
  BLOCK_TYPES.IF_AREA_FREEZE_READY_ELSE
];

export const ADVANCED_BOOLEAN_WRAPPERS = [
  BLOCK_TYPES.IF_BOOLEAN,
  BLOCK_TYPES.IF_BOOLEAN_ELSE
];

export const ADVANCED_BOOLEAN_VALUES = [
  BLOCK_TYPES.BOOLEAN_SENSOR_MATCHES,
  BLOCK_TYPES.BOOLEAN_HAVE_ENEMY_FLAG,
  BLOCK_TYPES.BOOLEAN_CAN_JUMP,
  BLOCK_TYPES.BOOLEAN_CAN_PLACE_BARRIER,
  BLOCK_TYPES.BOOLEAN_AREA_FREEZE_READY,
  BLOCK_TYPES.BOOLEAN_TEAMMATE_HAS_FLAG,
  BLOCK_TYPES.BOOLEAN_ON_MY_SIDE,
  BLOCK_TYPES.BOOLEAN_ON_ENEMY_SIDE,
  BLOCK_TYPES.LOGIC_AND,
  BLOCK_TYPES.LOGIC_OR,
  BLOCK_TYPES.LOGIC_NOT,
  BLOCK_TYPES.VALUE_COMPARE
];

export const ADVANCED_NUMBER_VALUES = [
  BLOCK_TYPES.VALUE_NUMBER,
  BLOCK_TYPES.VALUE_RUNNER_INDEX,
  BLOCK_TYPES.VALUE_DISTANCE_TO_TARGET,
  BLOCK_TYPES.VALUE_RANDOM_ROLL,
  BLOCK_TYPES.VALUE_PLAY_DIRECTION
];

export const ADVANCED_ALL_BLOCKS = [
  ...ADVANCED_BOOLEAN_WRAPPERS,
  ...ADVANCED_BOOLEAN_VALUES,
  ...ADVANCED_NUMBER_VALUES
];

export const ADVANCED_CAPSTONE_BLOCKS = [
  ...ADVANCED_ALL_BLOCKS,
  ...GENERIC_SENSOR_BLOCKS,
  ...MOVE_TOWARD_BLOCKS,
  ...TEAMMATE_FLAG_BLOCKS,
  ...TERRITORY_BLOCKS,
  ...AREA_FREEZE_BLOCKS,
  ...BARRIER_READY_BLOCKS,
  ...BARRIER_PLACEMENT_BLOCKS,
  ...JUMP_CONDITION_BLOCKS,
  ...JUMP_BLOCKS,
  ...EXTENDED_MOVEMENT_BLOCKS,
  BLOCK_TYPES.MOVE_RANDOMLY
];
